app = "valorant-profile-checker"
primary_region = "cdg"

[env]
  BASE_URL = "https://valorant.thomaswienecke.com"

[build]
    dockerfile = "Dockerfile"
    
[http_service]
  internal_port = 3000
  force_https = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
